AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120

Style/SafeNavigation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: nested
  SupportedStyles:
    - nested
    - compact

Style/LambdaCall:
  EnforcedStyle: call
  SupportedStyles:
    - braces
    - call
